name: Publish

# Triggers package publishing on each release creation
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install poetry, configure, and install packages
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          poetry config virtualenvs.in-project false
          poetry install --no-interaction
          poetry env info
      - name: Publish
        run: |
          poetry run poetry-dynamic-versioning
          # TODO: activate this
          # python -m poetry config pypi-token.pypi $PYPI_TOKEN
          # TODO: remove, only required for testing
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
          # TODO: remove -r test-pypi
          poetry publish --build -r test-pypi