name: Publish

# Triggers package publishing on each release creation
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install poetry, configure, and install packages
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          poetry config virtualenvs.in-project false
          poetry install --no-interaction
      - name: Publish
        run: |
          poetry run poetry-dynamic-versioning
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build